// const STEPS = [
//   {
//     id: "personal",
//     label: "Contact Information",
//     fields: [
//       { key: "FirstName",             label: "First Name",                        type: "text",   placeholder: "John" },
//       { key: "LastName",              label: "Last Name",                         type: "text",   placeholder: "Doe" },
//       { key: "Phone",                 label: "Phone Number",                      type: "tel",    placeholder: "+1 (555) 000-0000" },
//       { key: "MobilePhone",           label: "Mobile Number",                     type: "tel",    placeholder: "+1 (555) 000-0000" },
//       { key: "WhatsApp_Number__c",    label: "WhatsApp Number",                   type: "tel",    placeholder: "+1 (555) 000-0000" },
//       { key: "Email",                 label: "Email Address",                     type: "email",  placeholder: "john@example.com" },
//       { key: "City__c",               label: "City",                              type: "text",   placeholder: "New York" },
//       { key: "State__c",              label: "State / Province",                  type: "text",   placeholder: "NY" },
//       { key: "MailingCountryText__c", label: "Country",                           type: "text",   placeholder: "US" },
//       { key: "Time_Zone__c",          label: "Time Zone",                         type: "select", placeholder: "Select Time Zone",
//         options: ["Eastern (ET)", "Central (CT)", "Mountain (MT)", "Pacific (PT)", "Alaska (AKT)", "Hawaii (HT)", "UTC", "Other"] },
//       { key: "Source__c",             label: "Where did you hear about us?",      type: "select", placeholder: "Select source",
//         options: ["Google", "LinkedIn", "Facebook", "Friend / Referral", "Job Board", "Email", "Other"] },
//       { key: "resume",                label: "Upload Resume",                     type: "file",   placeholder: "" },
//     ],
//   },
//   {
//     id: "company",
//     label: "Job Preferences & Location",
//     fields: [
//       { key: "What_units_are_you_open_to__c",             label: "What units or positions are you open to?",                                                   type: "text",   placeholder: "e.g. ICU, ER, Med-Surg" },
//       { key: "What_shift_s_are_you_open_to__c",           label: "What shifts are you open to?",                                                               type: "text",   placeholder: "e.g. Days, Nights, Rotating" },
//       { key: "Location_s_Desired__c",                     label: "What parts of the US are you open to for job notifications?",                                type: "text",   placeholder: "e.g. Southeast, Midwest" },
//       { key: "Any_preferences_on_part_of_the_country__c", label: "Do you have preferences on part of the country?",                                            type: "text",   placeholder: "e.g. Prefer warm climates" },
//       { key: "Any_family_or_friends_in_the_US__c",        label: "Do you have any family or friends in the US?",                                               type: "text",   placeholder: "Yes / No / Details" },
//       { key: "Are_you_open_to_city_and_rural_areas__c",   label: "Are you open to city and rural areas?",                                                      type: "text",   placeholder: "Yes / No / City only" },
//       { key: "Max_Commuting_Distance_Time__c",            label: "Are you only looking locally? If yes, what is your max commuting distance or time?",         type: "text",   placeholder: "e.g. 30 miles / 45 min",  fullWidth: true },
//       { key: "Employment_Status__c",                      label: "What type of employment are you looking for?",                                               type: "select", placeholder: "Select employment type",
//         options: ["Full-Time", "Part-Time", "Per Diem", "Contract", "Internship"] },
//       { key: "Employment_Type__c",                        label: "Are you looking for permanent, travel or both?",                                             type: "select", placeholder: "Select preference",
//         options: ["Permanent", "Travel", "Both"] },
//     ],
//   },
//   {
//     id: "lead",
//     label: "Origin, Residence & Citizenship",
//     fields: [
//       { key: "Country_of_origin__c",                  label: "What country were you born in?",                                        type: "text", placeholder: "e.g. Philippines" },
//       { key: "Country_of_residence__c",               label: "What country do you currently live in?",                                type: "text", placeholder: "e.g. Canada" },
//       { key: "Country_of_Citizenship_1__c",           label: "What is your primary country of citizenship?",                         type: "text", placeholder: "e.g. United States" },
//       { key: "Country_of_Citizenship__c",             label: "Do you have citizenship in a second country?",                         type: "text", placeholder: "e.g. Australia or N/A" },
//       { key: "Applying_for_another_citizenship_1__c", label: "Are you currently applying for citizenship in another country?",       type: "text", placeholder: "Yes / No / Details",   fullWidth: true },
//       { key: "Moving_with_anyone_Pets__c",            label: "Are you moving with family members or pets?",                          type: "text", placeholder: "e.g. Spouse + 1 child" },
//       { key: "spouse_job",                            label: "Does your spouse need a job?",                                         type: "text", placeholder: "Yes / No" },
//     ],
//   },
// ];
const STEPS = [
  {
    id: "personal",
    label: "Contact Information",
    fields: [
      { key: "FirstName",             label: "First Name",                        type: "text",   placeholder: "John",                  required: true },
      { key: "LastName",              label: "Last Name",                         type: "text",   placeholder: "Doe",                   required: true },
      { key: "Phone",                 label: "Phone Number",                      type: "tel",    placeholder: "+1 (555) 000-0000",     required: true },
      { key: "MobilePhone",           label: "Mobile Number",                     type: "tel",    placeholder: "+1 (555) 000-0000",     required: false },
      { key: "countryCode",           label: "Country Code",                      type: "hidden",    value: "(+1)",                    required: false },
      { key: "WhatsAppNumber",    label: "WhatsApp Number",                   type: "tel",    placeholder: "+1 (555) 000-0000",     required: false },
      { key: "Email",                 label: "Email Address",                     type: "email",  placeholder: "john@example.com",      required: true },
      { key: "Password",              label: "Password",                          type: "password", placeholder: "Enter password",       required: true },
      { key: "ConfirmPassword",       label: "Confirm Password",                  type: "password", placeholder: "Confirm password",     required: true },
      { key: "City",               label: "City",                              type: "text",   placeholder: "New York",              required: true },
      { key: "State",              label: "State / Province",                  type: "text",   placeholder: "NY",                    required: true },
      { key: "MailingCountryText", label: "Country",                           type: "text",   placeholder: "US",                    required: true },
      { key: "TimeZone",          label: "Time Zone",                         type: "select", placeholder: "Select Time Zone",      required: true,
        options: ["Eastern", "Central", "Mountain"] },
      { key: "Source",             label: "Where did you hear about us?",      type: "select", placeholder: "Select source",         required: true,
        options: ["Google", "LinkedIn", "Facebook", "Friend / Referral", "Job Board", "Email", "Other"] },
      { key: "Attachment",                label: "Upload Resume",                     type: "file",   placeholder: "",                      required: true },
    ],
  },
  {
    id: "company",
    label: "Job Preferences & Location",
    fields: [
      { key: "What_units_are_you_open_to",             label: "What units or positions are you open to?",                                                   type: "text",   placeholder: "e.g. ICU, ER, Med-Surg",       required: true },
      { key: "What_shift_s_are_you_open_to",           label: "What shifts are you open to?",                                                               type: "text",   placeholder: "e.g. Days, Nights, Rotating",  required: true },
      { key: "Location_s_Desired",                     label: "What parts of the US are you open to for job notifications?",                                type: "text",   placeholder: "e.g. Southeast, Midwest",      required: true },
      { key: "Any_preferences_on_part_of_the_country", label: "Do you have preferences on part of the country?",                                            type: "text",   placeholder: "e.g. Prefer warm climates",    required: false },
      { key: "Any_family_or_friends_in_the_US",        label: "Do you have any family or friends in the US?",                                               type: "text",   placeholder: "Yes / No / Details",           required: false },
      { key: "Are_you_open_to_city_and_rural_areas",   label: "Are you open to city and rural areas?",                                                      type: "text",   placeholder: "Yes / No / City only",         required: true },
      { key: "Max_Commuting_Distance_Time",            label: "Are you only looking locally? If yes, what is your max commuting distance or time?",         type: "text",   placeholder: "e.g. 30 miles / 45 min",       required: false, fullWidth: true },
      { key: "Employment_Status",                      label: "What type of employment are you looking for?",                                               type: "select", placeholder: "Select employment type",        required: true,
        options: ["Full-Time", "Part-Time", "Per Diem", "Contract", "Internship"] },
      { key: "Employment_Type",                        label: "Are you looking for permanent, travel or both?",                                             type: "select", placeholder: "Select preference",             required: true,
        options: ["Permanent", "Travel", "Both"] },
    ],
  },
  {
    id: "lead",
    label: "Origin, Residence & Citizenship",
    fields: [
      { key: "Country_of_origin",                  label: "What country were you born in?",                                        type: "text", placeholder: "e.g. Philippines",        required: true },
      { key: "CountryOfResidence",               label: "What country do you currently live in?",                                type: "text", placeholder: "e.g. Canada",             required: true },
      { key: "Country_of_Citizenship_1",           label: "What is your primary country of citizenship?",                         type: "text", placeholder: "e.g. United States",      required: true },
      { key: "Country_of_Citizenship",             label: "Do you have citizenship in a second country?",                         type: "text", placeholder: "e.g. Australia or N/A",   required: false },
      { key: "Applying_for_another_citizenship_1", label: "Are you currently applying for citizenship in another country?",       type: "text", placeholder: "Yes / No / Details",      required: true, fullWidth: true },
      { key: "Moving_with_anyone_Pets",            label: "Are you moving with family members or pets?",                          type: "text", placeholder: "e.g. Spouse + 1 child",   required: false },
      { key: "Spouse_Employment_Need",                            label: "Does your spouse need a job?",                                         type: "text", placeholder: "Yes / No",                required: false },
    ],
  },
];

export default STEPS;
